name: Deploy note-taker-gpt

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy-dev:
    name: Deploy to dev environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libportaudio2 libportaudiocpp0 portaudio19-dev

      - name: Install Python libraries
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Syntax Check (Compile Bytecode)
        run: python -m compileall .

      - name: Kill background process
        run: pkill -f gui.py
